### ISSUE TITLE
Collision shape/RayCast problems

### ISSUE THREAD

**Issue by oidro** [CherrySodaPop/VoxelGame#6]
`clientPlayer`'s `playerLookingAt` property, when plugged into `World.get_block_gd`, gives weird results (e.g. reports looking at an air block when the player is looking at grass).

This could be an issue with the raycast, the chunk mesh's collision shape, rounding `Vector3` components to `isize`s on the Rust side, or a variety of other strange issues.

**Comment by CherrySodaPop** [comment]
Fixed in #7
